"""post-reset alignment

Revision ID: 4ceaf7529655
Revises: subscription
Create Date: 2025-08-13 15:41:06.814422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ceaf7529655'
down_revision: Union[str, None] = 'subscription'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_usage_periods_period_start', table_name='user_usage_periods')
    op.drop_index('ix_user_usage_periods_user_id', table_name='user_usage_periods')
    op.drop_table('user_usage_periods')
    op.alter_column('annotations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('annotations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_annotations_book_id', table_name='annotations')
    op.create_index(op.f('ix_annotations_id'), 'annotations', ['id'], unique=False)
    op.drop_constraint('annotations_book_id_fkey', 'annotations', type_='foreignkey')
    op.create_foreign_key(None, 'annotations', 'books', ['book_id'], ['id'])
    op.alter_column('bookmarks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('bookmarks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_bookmarks_book_id', table_name='bookmarks')
    op.create_index(op.f('ix_bookmarks_id'), 'bookmarks', ['id'], unique=False)
    op.drop_constraint('bookmarks_book_id_fkey', 'bookmarks', type_='foreignkey')
    op.create_foreign_key(None, 'bookmarks', 'books', ['book_id'], ['id'])

    # Create the ENUM type before altering the column
    filetype_enum = postgresql.ENUM('PDF', 'EPUB', 'TXT', name='filetype')
    bind = op.get_bind()
    filetype_enum.create(bind, checkfirst=True)

    # Convert existing values to the ENUM using an explicit USING clause
    op.alter_column(
        'books',
        'file_type',
               existing_type=sa.VARCHAR(length=50),
        type_=filetype_enum,
        existing_nullable=False,
        postgresql_using="UPPER(file_type)::filetype",
    )

    op.alter_column('books', 'is_processed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('books', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('books', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_books_user_id', table_name='books')
    op.drop_constraint('uq_books_pdf_id', 'books', type_='unique')
    op.drop_index('ix_books_pdf_id', table_name='books')
    op.create_index(op.f('ix_books_pdf_id'), 'books', ['pdf_id'], unique=True)
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    op.drop_constraint('books_user_id_fkey', 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'users', ['user_id'], ['id'])
    op.alter_column('highlights', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('highlights', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_highlights_book_id', table_name='highlights')
    op.create_index(op.f('ix_highlights_id'), 'highlights', ['id'], unique=False)
    op.drop_constraint('highlights_book_id_fkey', 'highlights', type_='foreignkey')
    op.create_foreign_key(None, 'highlights', 'books', ['book_id'], ['id'])
    op.alter_column('password_reset_tokens', 'used',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('password_reset_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('subscription_status', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('subscription_tier', sa.String(length=50), nullable=True))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'total_files_uploaded',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'total_tts_minutes',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('users', 'total_tts_minutes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('users', 'total_files_uploaded',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_column('users', 'subscription_tier')
    op.drop_column('users', 'subscription_status')
    op.drop_column('users', 'stripe_customer_id')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.alter_column('password_reset_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('password_reset_tokens', 'used',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_constraint(None, 'highlights', type_='foreignkey')
    op.create_foreign_key('highlights_book_id_fkey', 'highlights', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_highlights_id'), table_name='highlights')
    op.create_index('ix_highlights_book_id', 'highlights', ['book_id'], unique=False)
    op.alter_column('highlights', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('highlights', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key('books_user_id_fkey', 'books', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.drop_index(op.f('ix_books_pdf_id'), table_name='books')
    op.create_index('ix_books_pdf_id', 'books', ['pdf_id'], unique=False)
    op.create_unique_constraint('uq_books_pdf_id', 'books', ['pdf_id'], postgresql_nulls_not_distinct=False)
    op.create_index('ix_books_user_id', 'books', ['user_id'], unique=False)

    # Convert ENUM back to VARCHAR and drop ENUM type
    filetype_enum = postgresql.ENUM('PDF', 'EPUB', 'TXT', name='filetype')
    op.alter_column(
        'books',
        'file_type',
        existing_type=filetype_enum,
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
        postgresql_using="file_type::text",
    )
    filetype_enum.drop(op.get_bind(), checkfirst=True)

    op.alter_column('books', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('books', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('books', 'is_processed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_constraint(None, 'bookmarks', type_='foreignkey')
    op.create_foreign_key('bookmarks_book_id_fkey', 'bookmarks', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_bookmarks_id'), table_name='bookmarks')
    op.create_index('ix_bookmarks_book_id', 'bookmarks', ['book_id'], unique=False)
    op.alter_column('bookmarks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('bookmarks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_constraint(None, 'annotations', type_='foreignkey')
    op.create_foreign_key('annotations_book_id_fkey', 'annotations', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_annotations_id'), table_name='annotations')
    op.create_index('ix_annotations_book_id', 'annotations', ['book_id'], unique=False)
    op.alter_column('annotations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('annotations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_table('user_usage_periods',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('period_start', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('period_end', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('tts_minutes_used', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ai_queries_used', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('book_uploads_used', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_usage_periods_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_usage_periods_pkey'),
    sa.UniqueConstraint('user_id', 'period_start', name='uq_user_usage_period', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_user_usage_periods_user_id', 'user_usage_periods', ['user_id'], unique=False)
    op.create_index('ix_user_usage_periods_period_start', 'user_usage_periods', ['period_start'], unique=False)
    # ### end Alembic commands ###
